import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import CameraList from '../components/CameraList'
import FormAdd from '../components/FormAdd'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [camera, setCamera] = useState(null)
  const [showFormAdd, setShowFormAdd] = useState<boolean>(false)

  const onPressCamera = (camera) => {
    setCamera(camera);
  }

  const toggleShowFormAdd = () => {
    setShowFormAdd(!showFormAdd);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

        <div style={{ display: 'flex', flex: 1, flexDirection: 'row' }}>
         <div style={{ width: 300 }}>
          <div>
           <a href="#" onClick={toggleShowFormAdd}>Add</a>
          </div>

          <CameraList onClick={onPressCamera} />
          </div>
          <div style={{ flex: 1 }}>
            {camera ? camera.id : null}
          </div>
        </div>
      </main>

      {showFormAdd &&
        <div style={{ position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, background: 'red', flex: 1, justifyContent: 'center', alignItems: 'center', display: 'flex' }}>
          <FormAdd onClose={toggleShowFormAdd} />
        </div>
      }

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}vercel.svg`} alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
